-- Create table for all Indian States and Union Territories with population in crores
CREATE TABLE pune.indian_states_population (
    id SERIAL PRIMARY KEY,
    state_name VARCHAR(100) NOT NULL UNIQUE,
    population_crores NUMERIC(5, 2) NOT NULL,
    type VARCHAR(20) DEFAULT 'State'
);

INSERT INTO pune.indian_states_population (state_name, population_crores, type) VALUES
('Andhra Pradesh', 4.94, 'State'),
('Arunachal Pradesh', 0.14, 'State'),
('Assam', 3.12, 'State'),
('Bihar', 10.41, 'State'),
('Chhattisgarh', 2.55, 'State'),
('Goa', 0.15, 'State'),
('Gujarat', 6.04, 'State'),
('Haryana', 2.54, 'State'),
('Himachal Pradesh', 0.69, 'State'),
('Jharkhand', 3.30, 'State'),
('Karnataka', 6.11, 'State'),
('Kerala', 3.34, 'State'),
('Madhya Pradesh', 7.26, 'State'),
('Maharashtra', 11.24, 'State'),
('Manipur', 0.29, 'State'),
('Meghalaya', 0.30, 'State'),
('Mizoram', 0.11, 'State'),
('Nagaland', 0.20, 'State'),
('Odisha', 4.20, 'State'),
('Punjab', 2.77, 'State'),
('Rajasthan', 6.85, 'State'),
('Sikkim', 0.06, 'State'),
('Tamil Nadu', 7.21, 'State'),
('Telangana', 3.50, 'State'),
('Tripura', 0.37, 'State'),
('Uttar Pradesh', 19.98, 'State'),
('Uttarakhand', 1.01, 'State'),
('West Bengal', 9.13, 'State'),
('Andaman and Nicobar Islands', 0.04, 'Union Territory'),
('Chandigarh', 0.11, 'Union Territory'),
('Dadra and Nagar Haveli and Daman and Diu', 0.06, 'Union Territory'),
('Delhi', 1.68, 'Union Territory'),
('Jammu and Kashmir', 1.23, 'Union Territory'),
('Ladakh', 0.03, 'Union Territory'),
('Lakshadweep', 0.01, 'Union Territory'),
('Puducherry', 0.12, 'Union Territory');
