services: 
  postgres:
    build:
      context: .
      dockerfile: /dockerfiles/postgres.yml
    image: kayyum/kayyum_postgres:latest 
    container_name: postgres
    hostname: postgres 
    networks:
      app_net:
        ipv4_address: 172.28.0.10
    tty: true
    restart: unless-stopped
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TZ=Asia/Kolkata 
    ports:
      - "5432:5432"
      - "2222:22"
    volumes:
      - postgres_data:/var/lib/postgresql
    command: >
      bash -c '
      service ssh start && 
      service postgresql start && 
      if ! grep -q "listen_addresses" /etc/postgresql/16/main/postgresql.conf; then
        echo "listen_addresses = '\''*'\''" >> /etc/postgresql/16/main/postgresql.conf
        echo "host all all 0.0.0.0/0 scram-sha-256" >> /etc/postgresql/16/main/pg_hba.conf
        service postgresql restart
      fi && 
      tail -f /dev/null
      '

volumes:
  postgres_data:

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

#docker compose -f postgres_compose.yml up --build -d
# next time: docker compose -f postgres_compose.yml up  -d