#ansible:172.18.0.2; postgres:172.18.0.4; jenkins:172.18.0.3
[ubuntu_nodes]
ansible ansible_host=172.18.0.2 ansible_user=kayyum
postgres ansible_host=172.18.0.4 ansible_user=postgres
jenkins ansible_host=172.18.0.3 ansible_user=jenkins
