---
- name: sample
  hosts: all 
  gather_facts: yes
  become: true
  become_method: sudo 
  tasks:
    - name: free memory
      ansible.builtin.shell:
        cmd: |
          free -h
          lscpu | grep -e "Model name"
        executable: /bin/bash
      register: output 

    - name: output 
      ansible.builtin.debug:
        var: output.stdout_lines
