---
- name: Deploy SSH Public Key to Remote Servers
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure public key is present in authorized_keys
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
