FROM ubuntu:noble-20260911

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Kolkata

# Configure repositories, update, and install required tools and Ansible
RUN rm -f /etc/apt/sources.list && \
    rm -rf /var/lib/apt/lists/* && \
    echo "deb http://archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse" > /etc/apt/sources.list && \
    echo "deb http://archive.ubuntu.com/ubuntu/ noble-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb http://security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse" >> /etc/apt/sources.list && \
    apt-get update -y && \
    apt-get install -y \
    software-properties-common && \
    add-apt-repository --yes --update ppa:ansible/ansible && \
    apt-get install -y \
    iputils-ping \
    vim \
    curl \
    wget \
    net-tools \
    openssh-server \
    sshpass \
    python3 \
    python-is-python3 \
    sudo \
    python3-psycopg2 \
    ansible && \
    rm -rf /var/lib/apt/lists/*

# Create users if they don't exist and set passwords
RUN id -u kayyum >/dev/null 2>&1 || useradd -m -s /bin/bash kayyum && \
    id -u jenkins >/dev/null 2>&1 || useradd -m -s /bin/bash jenkins && \
    id -u postgres >/dev/null 2>&1 || useradd -m -s /bin/bash postgres && \
    echo "root:k" | chpasswd && \
    echo "kayyum:k" | chpasswd && \
    echo "jenkins:k" | chpasswd && \
    echo "postgres:k" | chpasswd

# Configure passwordless sudo for kayyum
RUN echo "kayyum ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/kayyum-policy && \
    chmod 440 /etc/sudoers.d/kayyum-policy

# Prepare SSH runtime directory
RUN mkdir -p /var/run/sshd

# Expose SSH port
EXPOSE 22